databases:
  - name: poker_DB
    databaseName: poker_db_38k9
    user: poker
    region: singapore

services:
  - type: web
    name: poker
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poker_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

